<?php

$I = new WebGuy($scenario);
$I->wantTo('Test the bugs edit page');
$I->amOnPage('admin/bugs/edit');

/** First check form cannot be sent if the user doesnt input any values **/
$I->amGoingTo('Submit user form with invalid values');
$I->click('Save');

$I->see("Clients_contacts_id can not be empty");
            $I->see("Url can not be empty");
            $I->see("Browser can not be empty");
            $I->see("Operating_system can not be empty");
            $I->see("Device can not be empty");
            $I->see("Severity can not be empty");
            $I->see("Reproduce can not be empty");
            $I->see("Description can not be empty");
            $I->see("Flagged can not be empty");
            $I->see("Fixed can not be empty");
            

$I->amGoingTo("Submit bugs form without a clients_contacts_id");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a url");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a browser");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a operating_system");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a device");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a severity");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a reproduce");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a description");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a flagged");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[fixed]", "Acceptance Test" );
                        $I->amGoingTo("Submit bugs form without a fixed");
                                        $I->click("Save");
                                        $I->fillField ( "bugs[clients_contacts_id]", "Acceptance Test" );
                        $I->fillField ( "bugs[url]", "Acceptance Test" );
                        $I->fillField ( "bugs[browser]", "Acceptance Test" );
                        $I->fillField ( "bugs[operating_system]", "Acceptance Test" );
                        $I->fillField ( "bugs[device]", "Acceptance Test" );
                        $I->fillField ( "bugs[severity]", "Acceptance Test" );
                        $I->fillField ( "bugs[reproduce]", "Acceptance Test" );
                        $I->fillField ( "bugs[description]", "Acceptance Test" );
                        $I->fillField ( "bugs[flagged]", "Acceptance Test" );
                        

?>